### Getting all expenses
GET http://localhost:8080/expenses

### creating new expense
POST http://localhost:8080/expenses
Content-Type: application/json

{
"expenseType":"travel",
"expenseAmount":500.0,
"currency":"Euro"
}

### Updating expense
PUT http://localhost:8080/expenses/2
Content-Type: application/json

{
  "expenseType":"Car",
  "expenseAmount":3002.0,
  "currency":"Euro"
}

### deleting expense
DELETE http://localhost:8080/expenses/1